Repository SOPT-all/35-COLLABORATION-WEB-ALIEXPRESS, pull requests merged in 2024-11, with the labels that each got.

#2 [INIT] 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/issue_template.yml
Labels: 🍀INIT🍀

#7 [INIT] react 프로젝트 초기 설정
  .gitignore
  eslint.config.js
  index.html
  package.json
  src/App.tsx
  src/main.tsx
  src/queryClient.ts
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 🍀INIT🍀

#5 [INIT] 풀리퀘스트 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: 🍀INIT🍀

#17 [FEAT] emotion css 적용을 위한 tsconfig.json 파일 내용 추가
  tsconfig.json
Labels: ⭐FEAT⭐

#19 [FIX] 이슈 템플릿 빈 문자열 오류 수정 및 스타일 수정
  .github/ISSUE_TEMPLATE/issue_template.yml
Labels: 🍀FIX🍀

#14 [INIT] prettier 설정
  .prettierrc
  package.json
  yarn.lock
Labels: 🍀INIT🍀

#27 [INIT] ESLint 설정
  .eslintrc.json
  eslint.config.js
  package.json
  yarn.lock
Labels: 🍀INIT🍀

#33 [FIX] 띰 가지고 다니지 말고 타입 가지고 다니기
  src/App.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: 🍀FIX🍀

#32 [INIT] 절대경로 설정
  package.json
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 🍀INIT🍀

#23 [FEAT] common button 컴포넌트 퍼블리싱
  src/components/button/outlineTextBtn/OutlineTextBtn.tsx
  src/components/button/outlineTextBtn/OutlineTextBtnStyle.ts
  src/components/button/textBtn/TextBtn.tsx
  src/components/button/textBtn/TextBtnStyle.ts
Labels: ⭐FEAT⭐

#24 [FEAT] 카테고리 버튼 컴포넌트 퍼블리싱
  src/components/button/categoryItemBtn/CategoryItemBtn.tsx
  src/components/button/categoryItemBtn/CategoryItemBtnStyle.ts
Labels: ⭐FEAT⭐

#34 [FEAT]common button 컴포넌트 퍼블리싱
  .eslintrc.json
  src/assets/icons/ic_message_black_24.svg
  src/components/button/contactBtn/ContactBtn.tsx
  src/components/button/contactBtn/ContactBtnStyle.ts
  src/components/button/emojiBtn/EmojiBtn.tsx
  src/components/button/emojiBtn/EmojiBtnStyle.ts
  src/components/button/likeBtn/LikeBtn.tsx
  src/components/button/likeBtn/LikeBtnStyle.ts
Labels: ⭐FEAT⭐

#37 [STYLE] common button theme 적용하기
  src/components/button/categoryItemBtn/CategoryItemBtn.tsx
  src/components/button/categoryItemBtn/CategoryItemBtnStyle.ts
  src/components/button/outlineTextBtn/OutlineTextBtn.tsx
  src/components/button/outlineTextBtn/OutlineTextBtnStyle.ts
  src/components/button/textBtn/TextBtn.tsx
  src/components/button/textBtn/TextBtnStyle.ts
  vite.config.ts
  yarn.lock
Labels: 🎨STYLE🎨

#43 [FEAT] Product 컴포넌트 퍼블리싱
  .eslintrc.json
  src/components/product/FreeTag.tsx
  src/components/product/FreeTagStyle.ts
  src/components/product/ProductCard.tsx
  src/components/product/ProductCardStyle.ts
Labels: ⭐FEAT⭐

#49 [CI/CD] vercel 배포 연결
  .github/workflow/auto-sync.yml
Labels: 🔧CI/CD🔧

#44 [FEAT] 상품 상세 페이지 상단 퍼블리싱
  package.json
  src/App.tsx
  src/assets/images/img_adapter_black.png
  src/assets/images/img_adapter_blue.png
  src/assets/images/img_adapter_cable_black.png
  src/assets/images/img_adapter_cable_white.png
  src/assets/images/img_adapter_pink.png
  src/assets/images/img_adapter_purple.png
  src/assets/images/img_adapter_white.png
  src/assets/images/img_banner_reward.png
  src/assets/images/img_product_sub1.png
  src/assets/images/img_product_sub2.png
  src/assets/images/img_product_sub3.png
  src/assets/images/img_product_sub4.png
  src/assets/images/img_product_sub5.png
  src/assets/images/img_product_sub6.png
  src/assets/images/productDetailImages.ts
  src/components/ProductInfo/ProductInfo.tsx
  src/components/ProductInfo/ProductInfoStyle.ts
  src/pages/NotFoundPage.tsx
  src/pages/OrderPage.tsx
  src/pages/ProductPage.tsx
  src/route/Route.tsx
  src/styles/theme.ts
  src/types/ProductInfoType.ts
  tsconfig.app.json
  yarn.lock
Labels: ⭐FEAT⭐

#54 [CICD] auto-sync-yml파일에 develop에 pr올릴때도 action돌아가도록 내용 추가
  .github/workflows/auto-sync.yml
  src/components/ProductInfo/ProductInfo.tsx
Labels: 🍀FIX🍀, 🔧CI/CD🔧

#58 [CICD] pull_request 이벤트에서도 base_ref가 main일 때 sync_push 작업이 실행되도록 내용 추가
  .github/workflows/auto-sync.yml
Labels: 🔧CI/CD🔧

#45 [FEAT] 헤더 푸터 만들기
  src/assets/icons/ic_arrowbottom_s_white_12.svg
  src/assets/icons/index.ts
  src/assets/images/Line 18.svg
  src/assets/images/Vector 7192.svg
  src/assets/images/img_flag_kor_l.svg
  src/assets/images/img_flag_kor_s.svg
  src/assets/images/img_logotype_l.svg
  src/assets/images/img_profile_30.svg
  src/components/button/categoryItemBtn/CategoryItemBtn.tsx
  src/components/button/categoryItemBtn/CategoryItemBtnStyle.ts
  src/components/button/contactBtn/ContactBtn.tsx
  src/components/button/emojiBtn/EmojiBtn.tsx
  src/components/button/likeBtn/LikeBtn.tsx
  src/components/footer/Footer.tsx
  src/components/footer/FooterStyle.ts
  src/components/header/orderHeader/OrderHeader.tsx
  src/components/header/orderHeader/OrderHeaderStyle.ts
  src/components/header/productHeader/Category.tsx
  src/components/header/productHeader/CategoryStyle.ts
  src/components/header/productHeader/MyList.tsx
  src/components/header/productHeader/MyListStyle.ts
  src/components/header/productHeader/ProductHeader.tsx
  src/components/header/productHeader/ProductHeaderStyle.ts
  src/constants/categoryList.ts
  src/constants/footerMsg.ts
  src/constants/myList.ts
Labels: ⭐FEAT⭐

#59 [FEAT] 연관상품 (ProductList) 띄우기
  src/components/product/ProductCard.tsx
  src/components/product/ProductCardList.tsx
  src/components/product/ProductCardListStyle.ts
  src/components/product/ProductCardStyle.ts
Labels: ⭐FEAT⭐

#76 [FEAT] 헤더 기능 구현
  src/components/header/productHeader/MyList.tsx
  src/constants/categoryList.ts
Labels: ⭐FEAT⭐

#71 [FEAT] 리뷰 컴포넌트 퍼블리싱
  src/assets/icons/index.ts
  src/assets/images/img_avata1.svg
  src/assets/images/img_avata3.svg
  src/assets/images/img_avata4.svg
  src/assets/images/img_avata5.svg
  src/assets/images/img_avata6.svg
  src/assets/images/img_avata7.svg
  src/components/productPage/review/review/Card.tsx
  src/components/productPage/review/review/CardList.tsx
  src/components/productPage/review/review/CardListStyle.ts
  src/components/productPage/review/review/CardStyle.ts
  src/components/productPage/review/review/FilterBtnStyle.ts
  src/components/productPage/review/review/OriginalTextBtn.tsx
  src/components/productPage/review/review/RenderStar.tsx
  src/components/productPage/review/review/ReviewPage.tsx
  src/components/productPage/review/review/ReviewPageStyle.ts
  src/components/productPage/review/review/ReviewTypeLabelStyle.ts
  src/components/productPage/review/review/Tab.tsx
  src/components/productPage/review/review/TabStyle.ts
  src/constants/userImg.ts
  src/constants/userReview.ts
Labels: ⭐FEAT⭐

#60 [FEAT] 상품 구매 컴포넌트 퍼블리싱
  src/App.tsx
  src/components/orderBox/OrderBox.tsx
  src/components/orderBox/OrderboxStyle.ts
  src/styles/theme.ts
Labels: ⭐FEAT⭐

#66 [FEAT] 상품 상세보기 및 안내 퍼블리싱
  src/assets/images/img_detail_xl.png
  src/components/infoTable/InfoTable.tsx
  src/components/infoTable/InfoTableStyle.ts
  src/components/productSummary/ProductSummaryStyle.ts
  src/components/productSummary/ProductSummay.tsx
Labels: ⭐FEAT⭐

#77 [FIX] 상품 컴포넌트 크기 조정
  src/components/product/ProductCard.tsx
  src/components/product/ProductCardStyle.ts
Labels: 🍀FIX🍀

#55 [FEAT] 주문 배송 페이지 사이드바 컴포넌트 퍼블리싱
  src/assets/images/img_appapproachqr.png
  src/components/constants/menuItems.ts
  src/components/orderDetail/sideBar/menuBar/menuBar.tsx
  src/components/orderDetail/sideBar/menuBar/menuBarStyle.ts
  src/components/orderDetail/sideBar/qrCode/qrCode.tsx
  src/components/orderDetail/sideBar/qrCode/qrCodeStyle.ts
  src/components/orderDetail/sideBar/sideBar.tsx
  src/components/orderDetail/sideBar/sideBarStyle.ts
  src/styles/theme.ts
Labels: ⭐FEAT⭐

#61 [FEAT] 주문 배송 페이지 주문 배송 정보 컴포넌트 퍼블리싱
  src/App.tsx
  src/components/orderDetail/orderInfo/buyerInfo/buyerInfo.tsx
  src/components/orderDetail/orderInfo/buyerInfo/buyerInfoStyle.ts
  src/components/orderDetail/orderInfo/orderInfo.tsx
  src/components/orderDetail/orderInfo/orderInfoStyle.ts
  src/components/orderDetail/orderInfo/purchaseInfo/purchaseInfo.tsx
  src/components/orderDetail/orderInfo/purchaseInfo/purchaseInfoStyle.ts
  src/constants/buyerInfo.ts
  src/styles/theme.ts
Labels: ⭐FEAT⭐

#84 [FEAT] 상품 페이지 컴포넌트 합치기
  src/components/ProductInfo/ProductInfo.tsx
  src/components/ProductInfo/ProductInfoStyle.ts
  src/components/header/productHeader/ProductHeaderStyle.ts
  src/components/orderBox/OrderboxStyle.ts
  src/components/product/ProductCardList.tsx
  src/components/product/ProductCardListStyle.ts
  src/components/product/RecommandedList.tsx
  src/components/product/RecommandedListStyle.ts
  src/components/productOrderBox/ProductOrderBox.tsx
  src/components/productPage/review/reviewTop/RatingPage.tsx
  src/components/productPage/review/reviewTop/TitleStyle.ts
  src/components/productSummary/ProductSummaryStyle.ts
  src/constants/sampleProducts.ts
  src/constants/userImg.ts
  src/layout/ProductLayout.tsx
  src/layout/layoutStyle.ts
  src/pages/ProductPage.tsx
  src/route/Route.tsx
  src/styles/global.ts
Labels: ⭐FEAT⭐

#89 [FEAT] 연관상품 API 연결
  .gitignore
  src/App.tsx
  src/apis/instance.ts
  src/apis/productPage/product/getProduct.ts
  src/apis/productPage/product/productQueries.ts
  src/components/product/ProductCardList.tsx
  src/constants/errorMessages.ts
  src/pages/ProductPage.tsx
Labels: ⭐FEAT⭐

#92 [FEAT] 주문 상세 페이지 구현
  src/components/orderDetail/orderHistory/orderHistoryStyle.ts
  src/components/orderDetail/orderInfo/orderInfoStyle.ts
  src/components/orderDetail/orderStatus/orderStatusStyle.ts
  src/components/orderDetail/productRecommend/productRecommendStyle.ts
  src/components/orderDetail/serviceIntroduce/serviceIntroduceStyle.ts
  src/components/orderDetail/sideBar/sideBarStyle.ts
  src/layout/OrderLayout.tsx
  src/layout/orderLayoutStyle.ts
  src/pages/OrderPage.tsx
  src/pages/orderPageStyle.ts
Labels: ⭐FEAT⭐

#94 [FEAT] 주문 완료 api
  src/apis/productPage/order/orderProduct.ts
  src/apis/productPage/order/orderQuery.ts
  src/assets/icons/ic_dot.svg
  src/assets/icons/index.ts
  src/components/ProductInfo/ProductInfo.tsx
  src/components/ProductInfo/ProductInfoStyle.ts
  src/components/button/starBtn/StarBtnStyle.ts
  src/components/orderBox/OrderBox.tsx
  src/components/orderBox/OrderboxStyle.ts
  src/components/recommandedProducts/RecommandedBoxStyle.ts
Labels: ⭐FEAT⭐

#98 [FEAT] 상품 정보 조회 api
  src/apis/productPage/product/getProduct.ts
  src/apis/productPage/product/getRelatedProducts.ts
  src/apis/productPage/product/productQueries.ts
  src/apis/productPage/product/relatedProductsQueries.ts
  src/components/ProductInfo/ProductInfo.tsx
  src/components/product/ProductCardList.tsx
  src/components/productOrderBox/ProductOrderBox.tsx
  src/constants/dummyProductResponse.ts
  src/types/ProductInfoType.ts
Labels: ⭐FEAT⭐

#97 [FIX] 뷰 피그마에 맞게 수정
  src/components/footer/FooterStyle.ts
  src/components/header/productHeader/CategoryStyle.ts
  src/components/header/productHeader/MyListStyle.ts
  src/components/productPage/review/review/FilterBtn.tsx
  src/components/productPage/review/review/FilterBtnStyle.ts
  src/components/productPage/review/reviewTop/Title.tsx
  src/components/productPage/review/reviewTop/TitleStyle.ts
Labels: 🍀FIX🍀

#112 [FEAT] 주문내역 api 연결
  src/apis/orderPage/getOrders.ts
  src/apis/orderPage/orderQueries.ts
  src/components/orderDetail/orderHistory/orderHistory.tsx
  src/components/orderDetail/orderHistory/orderHistoryStyle.ts
  src/constants/dummyOrderHistory.ts
  src/constants/orderHisotry.ts
Labels: ⭐FEAT⭐

#119 [STYLE] 헤더 요구사항 반영
  src/components/header/orderHeader/OrderHeaderStyle.ts
  src/components/header/productHeader/ProductHeader.tsx
  src/components/header/productHeader/ProductHeaderStyle.ts
Labels: 🎨STYLE🎨
